### ISSUE TITLE
aux_reset_avr.py not functional

### ISSUE THREAD

**Issue by x8-999-github** [newaetech/chipwhisperer#142]
the aux reset scripts on the develop branch are not working.

```
execfile('/home/why/projects/chipwhisperer/software/chipwhisperer/capture/scripts/aux_reset_avr.py')
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/why/projects/chipwhisperer/software/chipwhisperer/capture/scripts/aux_reset_avr.py", line 12, in <module>
    AVRResetter = ResetAVR()
TypeError: __init__() takes exactly 2 arguments (1 given)
```

The python code looks like this:
```
class ResetAVR(object):
    def __init__(self, path):
        self._stk_path = path
        self._part = "atmega328p"
        
    def reset(scope, target, project):
        ret = call([self._stk_path, "-d%s" % self._part, "-s", "-cUSB"])

        if int(ret) != 0:
            raise IOError("Error Calling Stk500.exe")

        time.sleep(1)
```

**Comment by FranzHeubach** [comment]
I am going to change the title and remove the aux_reset_cw1173.py as this issue does not mention any thing related to that script.

**Comment by alex-dewar** [comment]
New CW5 release with Jupyter notebook interface no longer has these reset scripts, so closing this issue.
