### ISSUE TITLE
setup_cwlist_xmega_password.py reset does not work

### ISSUE THREAD

**Issue by x8-999-github** [newaetech/chipwhisperer#143]
xmega_password reset also does not work

```
# Set up aux module to reset target before capture
resetter = ResetCW1173(xmega=True, delay_ms=1200)
aux_list.register(resetter.resetThenDelay, "before_trace")
```

```
execfile('/home/why/projects/chipwhisperer/software/chipwhisperer/capture/scripts/setup_cwlite_xmega_password.py')
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/why/projects/chipwhisperer/software/chipwhisperer/capture/scripts/setup_cwlite_xmega_password.py", line 34, in <module>
    resetter = ResetCW1173(xmega=True, delay_ms=1200)
TypeError: __init__() got an unexpected keyword argument 'xmega'
```

python code:
```
class ResetCW1173(object):
    """Reset an AVR/XMEGA via the PDI/ISP interface.
    
    This class must be initialized with 2 values:
    - Delay: How long to wait between device reset and scope arm
    - pin: (string) to identify pin to toggle
        XMEGA: use 'pdic', AVR and STM32Fx use 'nrst'
    
    Then, there are three self-explanatory functions that can be registered:
    - reset(): no delay. Useful for testing
    - resetThenDelay(): Useful for before_arm
    - delayThenReset(): Useful for after_arm
    
    Note that resetThenDelay() before arming is more consistent (resetting the 
    device can accidentally cause a trigger event) but delayThenReset() after 
    arming allows for a shorter delay between the reset and the scope
    measurement. 
    """
    
    def __init__(self, delay_ms, pin='nrst'):
        self._delay_ms = delay_ms
        self._pin = pin
```

**Comment by FranzHeubach** [comment]
I apologize for that, the xmega argument was deprecated in favor of the pin argument but I did not keep backwards compatibility. I pushed a change to introduce backwards compatibility and deprecation warnings to reduce future confusion.
