### ISSUE TITLE
Device has no langid Windows 64 Bit Python

### ISSUE THREAD

**Issue by alex-dewar** [newaetech/chipwhisperer#199]
64 bit versions of Python on Windows may fail to connect to a ChipWhisperer with the traceback:

```python
>>> scope = cw.scope()
Traceback (most recent call last):
  File "c:\users\user\code\term2\chipwhisperer\software\chipwhisperer\hardware\naeusb\naeusb.py", line 291, in txrx
    response = self.get_possible_devices(payload)
  File "c:\users\user\code\term2\chipwhisperer\software\chipwhisperer\hardware\naeusb\naeusb.py", line 420, in get_possible_devices
    devlist = [{'sn': d.serial_number, 'product': d.product, 'pid': d.idProduct, 'vid': d.idVendor} for d in devlist]
  File "c:\users\user\code\term2\chipwhisperer\software\chipwhisperer\hardware\naeusb\naeusb.py", line 420, in <listcomp>
    devlist = [{'sn': d.serial_number, 'product': d.product, 'pid': d.idProduct, 'vid': d.idVendor} for d in devlist]
  File "C:\Users\User\Downloads\WPy-3710\python-3.7.1.amd64\lib\site-packages\pyusb-1.0.2-py3.7.egg\usb\core.py", line 830, in serial_number
    self._serial_number = util.get_string(self, self.iSerialNumber)
  File "C:\Users\User\Downloads\WPy-3710\python-3.7.1.amd64\lib\site-packages\pyusb-1.0.2-py3.7.egg\usb\util.py", line 314, in get_string
    raise ValueError("The device has no langid")
ValueError: The device has no langid
Traceback (most recent call last):
  File "c:\users\user\code\term2\chipwhisperer\software\chipwhisperer\capture\scopes\openadc_interface\naeusbchip.py", line 75, in con
    possible_sn = self.dev.get_possible_devices(nae_products)
  File "c:\users\user\code\term2\chipwhisperer\software\chipwhisperer\capture\scopes\cwhardware\ChipWhispererLite.py", line 48, in get_possible_devices
    return self._cwusb.get_possible_devices(idProduct=idProduct)
  File "c:\users\user\code\term2\chipwhisperer\software\chipwhisperer\hardware\naeusb\naeusb.py", line 537, in get_possible_devices
    return self.usbseralizer.get_possible_devices(idProduct)
  File "c:\users\user\code\term2\chipwhisperer\software\chipwhisperer\hardware\naeusb\naeusb.py", line 129, in get_possible_devices
    return self.process_rx(self.txrx(tx=cmdpacket))
  File "c:\users\user\code\term2\chipwhisperer\software\chipwhisperer\hardware\naeusb\naeusb.py", line 149, in process_rx
    raise payload
ValueError: The device has no langid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<pyshell#9>", line 1, in <module>
    scope = cw.scope()
  File "c:\users\user\code\term2\chipwhisperer\software\chipwhisperer\__init__.py", line 124, in scope
    scope.con(sn)
  File "c:\users\user\code\term2\chipwhisperer\software\chipwhisperer\capture\scopes\base.py", line 65, in con
    if self._con(sn):
  File "c:\users\user\code\term2\chipwhisperer\software\chipwhisperer\capture\scopes\OpenADC.py", line 130, in _con
    self.scopetype.con(sn)
  File "c:\users\user\code\term2\chipwhisperer\software\chipwhisperer\capture\scopes\openadc_interface\naeusbchip.py", line 90, in con
    raise Warning('Could not connect to "%s". It may have been disconnected, is in an error state, or is being used by another tool.' % self.getName())
Warning: Could not connect to "NewAE USB (CWLite/CW1200)". It may have been disconnected, is in an error state, or is being used by another tool.
```

This appears to be an issue with the wrong libusb0 backend being loaded, which should have been handled by https://github.com/newaetech/chipwhisperer/blob/ec058372fd883f6dc9f8464bc0d113e13f0d08c7/software/chipwhisperer/hardware/naeusb/naeusb.py#L390-L411 (perhaps the exception changed?).  The exception appears to get raised when trying to access the serial number (getter function disguised as a variable?).

Interestingly, calling the second `usb.core.find()` that specifies the location of libusb0 before calling `cw.scope()` seems to fix things.

**Comment by alex-dewar** [comment]
This error seems to be a bit stranger than first anticipated. Catching the error inside the `find_possible_devices()` method, loading the new `libusb0.dll`, and retrying the `usb.core.find()` still fails, but subsequent calls to `cw.scope()` succeed.

This might be a weird import issue, so this error might need to be handled in the same spot where the old langid exception was caught and given more context: https://github.com/newaetech/chipwhisperer/blob/ec058372fd883f6dc9f8464bc0d113e13f0d08c7/software/chipwhisperer/capture/scopes/openadc_interface/naeusbchip.py#L68-L90.

Simply calling `libusb0.get_backend()` with the proper `find_library` argument before calling `cw.scope()` fixes things.
