### ISSUE TITLE
Can't get Scope to connect on jupyter notebook

### ISSUE THREAD

**Issue by ryancor** [newaetech/chipwhisperer#309]
`scope = cw.scope()`
```
Traceback (most recent call last):
  File "c:\users\ryancor\chipwhisperer5_64\chipwhisperer\software\chipwhisperer\hardware\naeusb\naeusb.py", line 314, in txrx
    response = self.get_possible_devices(payload)
  File "c:\users\ryancor\chipwhisperer5_64\chipwhisperer\software\chipwhisperer\hardware\naeusb\naeusb.py", line 456, in get_possible_devices
    devlist = [{'sn': d.serial_number, 'product': d.product, 'pid': d.idProduct, 'vid': d.idVendor} for d in devlist]
  File "c:\users\ryancor\chipwhisperer5_64\chipwhisperer\software\chipwhisperer\hardware\naeusb\naeusb.py", line 456, in <listcomp>
    devlist = [{'sn': d.serial_number, 'product': d.product, 'pid': d.idProduct, 'vid': d.idVendor} for d in devlist]
  File "C:\Users\ryancor\ChipWhisperer5_64\WPy64-3740\python-3.7.4.amd64\lib\site-packages\usb\core.py", line 852, in serial_number
    self._serial_number = util.get_string(self, self.iSerialNumber)
  File "C:\Users\ryancor\ChipWhisperer5_64\WPy64-3740\python-3.7.4.amd64\lib\site-packages\usb\util.py", line 311, in get_string
    langids = dev.langids
  File "C:\Users\ryancor\ChipWhisperer5_64\WPy64-3740\python-3.7.4.amd64\lib\site-packages\usb\core.py", line 839, in langids
    self._langids = util.get_langids(self)
  File "C:\Users\ryancor\ChipWhisperer5_64\WPy64-3740\python-3.7.4.amd64\lib\site-packages\usb\util.py", line 270, in get_langids
    0
  File "C:\Users\ryancor\ChipWhisperer5_64\WPy64-3740\python-3.7.4.amd64\lib\site-packages\usb\control.py", line 175, in get_descriptor
    data_or_wLength = desc_size)
  File "C:\Users\ryancor\ChipWhisperer5_64\WPy64-3740\python-3.7.4.amd64\lib\site-packages\usb\core.py", line 1059, in ctrl_transfer
    self._ctx.managed_open()
  File "C:\Users\ryancor\ChipWhisperer5_64\WPy64-3740\python-3.7.4.amd64\lib\site-packages\usb\core.py", line 113, in wrapper
    return f(self, *args, **kwargs)
  File "C:\Users\ryancor\ChipWhisperer5_64\WPy64-3740\python-3.7.4.amd64\lib\site-packages\usb\core.py", line 131, in managed_open
    self.handle = self.backend.open_device(self.dev)
  File "C:\Users\ryancor\ChipWhisperer5_64\WPy64-3740\python-3.7.4.amd64\lib\site-packages\usb\backend\libusb1.py", line 804, in open_device
    return _DeviceHandle(dev)
  File "C:\Users\ryancor\ChipWhisperer5_64\WPy64-3740\python-3.7.4.amd64\lib\site-packages\usb\backend\libusb1.py", line 652, in __init__
    _check(_lib.libusb_open(self.devid, byref(self.handle)))
  File "C:\Users\ryancor\ChipWhisperer5_64\WPy64-3740\python-3.7.4.amd64\lib\site-packages\usb\backend\libusb1.py", line 600, in _check
    raise NotImplementedError(_strerror(ret))
NotImplementedError: Operation not supported or unimplemented on this platform
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-14-55deba0a9ef7> in <module>
----> 1 scope = cw.scope()

c:\users\ryancor\chipwhisperer5_64\chipwhisperer\software\chipwhisperer\__init__.py in scope(scope_type, sn)
    216     from chipwhisperer.common.utils.util import get_cw_type
    217     if scope_type is None:
--> 218         scope_type = get_cw_type(sn)
    219     scope = scope_type()
    220     scope.con(sn)

c:\users\ryancor\chipwhisperer5_64\chipwhisperer\software\chipwhisperer\common\utils\util.py in get_cw_type(sn)
    521 
    522     cwusb = NAEUSB()
--> 523     possible_sn = cwusb.get_possible_devices(idProduct=possible_ids)
    524     name = ""
    525     if len(possible_sn) == 0:

c:\users\ryancor\chipwhisperer5_64\chipwhisperer\software\chipwhisperer\hardware\naeusb\naeusb.py in get_possible_devices(self, idProduct)
    614 
    615     def get_possible_devices(self, idProduct):
--> 616         return self.usbseralizer.get_possible_devices(idProduct)
    617 
    618     def con(self, idProduct=[0xACE2], connect_to_first=False, serial_number=None):

c:\users\ryancor\chipwhisperer5_64\chipwhisperer\software\chipwhisperer\hardware\naeusb\naeusb.py in get_possible_devices(self, idProduct)
    132         """Get a list of connected USB devices."""
    133         cmdpacket = self.make_cmd(self.GET_POSSIBLE_DEVICES, idProduct)
--> 134         return self.process_rx(self.txrx(tx=cmdpacket))
    135 
    136     def process_rx(self, inp):

c:\users\ryancor\chipwhisperer5_64\chipwhisperer\software\chipwhisperer\hardware\naeusb\naeusb.py in process_rx(self, inp)
    152 
    153         if resp == self.ERROR:
--> 154             raise payload
    155 
    156         return payload

NotImplementedError: Operation not supported or unimplemented on this platform
```

**Comment by ryancor** [comment]
Nevermind this ticket can be closed
