### ISSUE TITLE
CWNANO: Changing scope.adc.clk_src results in a TypeError

### ISSUE THREAD

**Issue by R-Bas** [newaetech/chipwhisperer#371]
OS: Ubuntu 20.10
Python version: 3.8.10
Branch: Develop
Firmware: {'major': 0, 'minor': 50, 'debug': 0} (upgraded with scope.upgrade_firmware())

Trying to set scope.adc.clk_src to a new value results in the following error:
```
Traceback (most recent call last):
  File "./bug.py", line 5, in <module>
    scope.adc.clk_src = "ext"
  File ".../chipwhisperer/software/chipwhisperer/common/utils/util.py", line 353, in __setattr__
    super(DisableNewAttr, self).__setattr__(name, value)
  File ".../chipwhisperer/software/chipwhisperer/capture/scopes/cwnano.py", line 121, in clk_src
    self.usb.sendCtrl(self.USB_ADCLK_SET, 0, 5)
  File ".../chipwhisperer/software/chipwhisperer/hardware/naeusb/naeusb.py", line 555, in sendCtrl
    self.usbseralizer.sendCtrl(cmd, value, data)
  File ".../chipwhisperer/software/chipwhisperer/hardware/naeusb/naeusb.py", line 331, in sendCtrl
    self.handle.controlWrite(0x41, cmd, value, 0, data, timeout=self._timeout)
  File ".../.local/lib/python3.8/site-packages/usb1/__init__.py", line 1330, in controlWrite
    data, _ = create_initialised_buffer(data)
  File ".../.local/lib/python3.8/site-packages/usb1/__init__.py", line 176, in create_initialised_buffer
    string_type = c_char * len(init)
TypeError: object of type 'int' has no len()
```

Minimal code to reproduce the error (setting clk_src to "int" produces the same result):
```Python
#!/bin/python3
import chipwhisperer as cw

scope = cw.scope()
scope.adc.clk_src = "ext"
```

Any ideas why this happens ?

**Comment by alex-dewar** [comment]
Thanks for the report! It should be fixed by 42efec4b14520eebe0a77fb45f77a0e6720ba592.
